version: '3.4'

services: 
  api:
    container_name: budgetsnap_api
    build:
      context: .
      dockerfile: BudgetSnap.Api/Dockerfile
    ports:
      - 32780:80
    networks:
      - budgetsnap

networks:
  budgetsnap:
