version: '3.4'

services: 
  api:
    container_name: budgetsnap_api
    build:
      context: .
      dockerfile: BudgetSnap.Api/Dockerfile
    ports:
      - 32780:80
    networks:
      - budgetsnap
  web:
    container_name: budgetsnap_web
    build:
      context: .
      dockerfile: BudgetSnap.Web/Dockerfile
    ports:
      - 32781:80
    networks:
      - budgetsnap
      
  identity:
    container_name: budgetsnap_identityserver
    build:
      context: .
      dockerfile: BudgetSnap.IdentityServer/Dockerfile
    ports:
      - 32782:80
    networks:
      - budgetsnap
      
  sql:
    container_name: budgetsnap_sql
    build:
      context: .
      dockerfile: docker/sql/Dockerfile
    ports:
      - 14333:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssword
      - MSSQL_SA_USER=sa
      - MSSQL_COLLATION=Latin1_General_CS_AS
    networks:
      - budgetsnap

networks:
  budgetsnap:
