version: '3.4'

services: 
  api:
    container_name: budgetsnap_api
    build:
      context: .
      dockerfile: BudgetSnap.Api/Dockerfile
    ports:
      - 32780:80
    networks:
      - budgetsnap
  web:
    container_name: budgetsnap_web
    build:
      context: .
      dockerfile: BudgetSnap.Web/Dockerfile
    ports:
      - 32781:80
    networks:
      - budgetsnap
      
  identity:
    container_name: budgetsnap_identityserver
    build:
      context: .
      dockerfile: BudgetSnap.IdentityServer/Dockerfile
    ports:
      - 32782:80
    networks:
      - budgetsnap

networks:
  budgetsnap:
